---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: quotations
    directory: Casks
    homepage: "https://github.com/veerendra2/quotations"
    description: "A tool to display random inspirational quotes and famous dialogues from movies and TV shows on your CLI. 😎"
    url:
      verified: github.com/veerendra2/quotations
      template: "https://github.com/veerendra2/quotations/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    caveats: >-
      ℹ️ To display a random quote when terminal opens, add it to your shell

      💡 Example for Bash:

      echo "quotations" >> ~/.bashrc
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/quotations"]
          end
    repository:
      owner: veerendra2
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
